name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ci
        run: npm ci
      - name: build
        run: npm run build 
      - name: 'Upload output'
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./.output
          retention-days: 5
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: ci
        run: npm ci
      - name: ESLint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - uses: actions/checkout@v3
      - name: ci
        run: npm ci
      - name: setup dynamodb
        run: aws dynamodb create-table --cli-input-json file:///event_store/dynamodb_events_table.json --endpoint-url http://localhost:8000
      - name: test
        run: npm run test:coverage
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-northeast-1
